package com.fivvy.backend.challenge.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

@Data
@NoArgsConstructor
@DynamoDBTable(tableName = "disclaimer")
public class Disclaimer {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute(attributeName = "name")
    private String name;
    @DynamoDBAttribute(attributeName = "text")
    private String text;
    @DynamoDBAttribute(attributeName = "version")
    private String version;

    @DynamoDBAttribute(attributeName = "create_at")
    private Date createAt = new Date();

    @DynamoDBAttribute(attributeName = "update_at")
    private Date updateAt;

    public Disclaimer (String name, String text, String version){
        this.name = name;
        this.text = text;
        this.version = version;
    }
}
